# Generated by Django 2.1.5 on 2019-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0015_auto_20190125_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='images',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
